config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :users do
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     passwords: 'users/passwords',
     registrations: 'users/registrations'
   }
   root to: 'homes#top'
   get '/homes/about' => 'homes#about', as: 'homes_about'
   get 'users/timeline' => 'users#timeline', as: 'user_timeline'
   get 'users/:id/like_post' => 'users#like_post', as: 'user_like_post'
   get '/users/search_user_index' => 'users#search_user_index', as: 'search_user_index'
   resources :users, only: [:index, :show, :edit, :update] do
     get 'events/index' => 'events#index', as: 'events'
   end
   get '/users/:id/follow_index' => 'users#follow_index', as: 'user_follow'
   get '/users/:id/follower_index' => 'users#follower_index', as: 'user_follower'
   get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
   patch '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
   resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
     resources :likes, only: [:create, :destroy]
     resources :comments, only: [:create, :destroy]
     get '/comments/:id/new_reply' => 'comments#new_reply', as: 'new_reply'
     post '/comments/:id/reply_create' => 'comments#reply_create', as: 'reply_create'
   end
   get '/posts/:id/show_like_users' => 'posts#show_like_users', as: 'show_like_users'
   get '/posts/confirm' => 'posts#confirm', as: 'posts_confirm'
  resources :relationships, only: [:destroy, :create]
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :contacts, only: [:new, :create]
  get 'contacts/complete' => 'contacts#complete', as: 'contact_complete'
  end

  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  namespace :admins do
  get "/homes/top" => "homes#top", as: "homes"
  get '/users/search_user_index' => 'users#search_user_index', as: 'search_user_index'
  get '/users/:id/follow_index' => 'users#follow_index', as: 'user_follow'
  get '/users/:id/follower_index' => 'users#follower_index', as: 'user_follower'
  resources :users, only: [:index, :show, :update]
  get '/posts/search_post_index' => 'posts#search_post_index', as: 'search_post_index'
  resources :posts, only: [:index, :show, :destroy] do
    resources :comments, only: [:destroy]
  end
  get '/posts/:id/show_like_users' => 'posts#show_like_users', as: 'show_like_users'


  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  layout 'admins'
  before_action :authenticate_admin!
  before_action :set_post, only: [:show, :show_like_users, :destroy]
  def index
    @posts = Post.all.order(created_at: :desc).order(updated_at: :desc).page(params[:page]).per(10)
     # ransackの投稿内容の検索結果を表示するための変数を定義
    @q = @posts.ransack(params[:q])
    @search_posts = @q.result(distinct: true)
  end

  def search_post_index
    # ransackの投稿内容の検索結果を表示するための変数を定義
     @q = Post.ransack(params[:q])
     @posts = @q.result(distinct: true).order(created_at: :desc).order(updated_at: :desc).page(params[:page]).per(10)
  end

  def show
    # @post = Post.find(params[:id])
    @comments = @post.comments.where(parent_id: nil)
    @comment = @post.comments.new
    @comment_reply = @post.comments.new
  end

  def show_like_users
    # @post = Post.find(params[:id])
    @likes = Like.where(post_id: @post.id).order(updated_at: :desc).page(params[:page]).per(10)
  end

  def destroy
    # @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admins_posts_path
      flash[:destroy] = "投稿を削除しました。"
    else
      render :show
    end
  end
  
  
  private
  
  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  layout 'admins'
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :update, :follow_index, :follower_index]

  def index
    @users = User.all.order(updated_at: :desc).page(params[:page]).per(10)
    @q = @users.ransack(params[:q])
    @search_uesrs = @q.result(distinct: true)
  end

  def search_user_index
    # ransackのユーザーの検索結果を表示するための変数を定義
     @q = User.ransack(params[:q])
     @users = @q.result(distinct: true).order(created_at: :desc).order(updated_at: :desc).page(params[:page]).per(10)
  end

  def show
    @posts = @user.posts.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def follow_index
    @followings = @user.followings.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def follower_index
    @followers = @user.followers.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def update
    @user.update(user_params)
    # 退会フラグtrue変更後にユーザーの投稿、いいね、コメントを全て削除し、他のユーザーに表示されないようにする
    if @user.is_deleted == true
      @user.posts.destroy_all
      @user.likes.destroy_all
      @user.comments.destroy_all
      redirect_to admins_user_path(@user.id)
    else
      redirect_to admins_user_path(@user.id)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:is_deleted)
  end

end

app/controllers/users/chats_controller.rb
class Users::ChatsController < ApplicationController


    def create
      # form_withで送られてきたパラメータが入っているかを条件分岐で確認
      if UserRoom.where(user_id: params[:chat][:user_id], room_id: params[:chat][:room_id]).present?
        # trueであればuseer_idをmergeしてメッセージを作成する
        @chat = Chat.create(params.require(:chat).permit(:room_id, :user_id, :message).merge(user_id: current_user.id))
        respond_to do |format|
          format.html { redirect_to "room_path(params[:chat][:room_id])" }
          # render 'chat'でchat.json.jbuilderでマッピングした値を返すようにする
          format.json { render 'chat', handlers: 'jbuilder' }

        end
      else
        flash[:alert] = "メッセージ送信に失敗しました。"
        redirect_to room_path
      end
    end

end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :set_post, only: [:create, :new_reply, :reply_create]
  
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      redirect_to post_path(@post.id)
    else
      # posts_controllerのshowへrenderするために変数を定義
      @post = Post.find(params[:post_id])
      @like = @post.likes.find_by(user_id: current_user.id)
      @comments = @post.comments.where(parent_id: nil)
      # @post.comments.new
      @comment_reply = @post.comments.new
      render "users/posts/show"
    end
  end

  def new_reply
    @comment = Comment.find_by(post_id: @post.id, id: params[:id])
    @comment_reply = @post.comments.new
  end

  def reply_create
    @comment_reply = current_user.comments.new(comment_params)
    @comment_reply.post_id = @post.id
    if @comment_reply.save
      redirect_to post_path(@post.id)
    else
      @post = Post.find(params[:post_id])
      @comment = Comment.find_by(post_id: @post.id, id: params[:id])
      render "new_reply"
    end
  end


  def destroy
    if @comment = Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
      redirect_to post_path(params[:post_id])
    else
      redirect_to post_path(params[:post_id])
    end
  end

  private
  
  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:comment, :parent_id)
  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end
  
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to contact_complete_path
    else
      render :new
    end
  end
  
  def complete
  end
  
  private
  
  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
  
end

app/controllers/users/events_controller.rb
class Users::EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to user_events_path(@event.user_id)
    else
      render :new
    end
  end

  def index
    @user = User.find(params[:user_id])

    #jsonでeventテーブルのレコードを読み込むとindex.json.jbuilderで定義したstartとendがstart_date,end_dateになっていてカレンダーに表示できない現象あり。
    #対応として、ASでstart,endに変換する。
    @events = Event.where(user_id: @user.id).select('id, user_id, title, content, start_date AS start, end_date AS end')
  end

  def show
  end

  def edit
    # 他のユーザーがアクセスしようとしたときに遷移させないために条件分岐
    if @event.user_id != current_user.id
      if user_signed_in?
        redirect_to user_path(current_user.id)
      else
        redirect_to new_user_session_path
      end
    end
  end

  def update
    if @event.update(event_params)
      redirect_to user_events_path(user_id: current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to user_events_path(user_id: current_user.id)
  end

  private
  
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:user_id, :title, :content, :start_date, :end_date)
  end


end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
  before_action :set_like, only: [:create, :destroy]

  def create
    @like = current_user.likes.new(post_id: @post.id)
    @like.save
  end

  def destroy
    @like = current_user.likes.find_by(post_id: @post.id, id: params[:id])
    @like.destroy
  end
  
  private
  
  def set_like
    @post = Post.find(params[:post_id])
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :show_like_users, :edit, :update, :destroy]
  
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge({user_id: current_user.id}))
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def index
    @user = User.find(current_user.id)
    # ransackの投稿内容の検索結果を表示するための変数を定義
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).where(user_id: @user).order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    # @post = Post.find(params[:id])
    @like = @post.likes.find_by(user_id: current_user.id)
    @comments = @post.comments.where(parent_id: nil)
    @comment = @post.comments.new
    @comment_reply = @post.comments.new
    @post.comments.each do |comment|
    end

  end

  def show_like_users
    # @post = Post.find(params[:id])
    @likes = Like.where(post_id: @post.id).order(updated_at: :desc).page(params[:page]).per(10)
  end

  def edit
    # @post = Post.find(params[:id])
    # 他のユーザーがアクセスしようとしたときに遷移させないために条件分岐
    if @post.user_id != current_user.id
      if user_signed_in?
        redirect_to user_path(current_user.id)
      else
        redirect_to new_user_session_path
      end
    end
  end

  def update
    # @post = Post.find(params[:id])
    if @post.update(post_params.merge({user_id: current_user.id}))
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  private
  
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
     user_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  #def after_inactive_sign_up_path_for(resource)
    #super(resource)
  #end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  
  def create
    @user = User.find(params[:follow_id])
    @following = current_user.follow(@user)
    if @following.save
      redirect_to @user
    else
      redirect_to @user
    end
  end
  
  
  def destroy
    @user = User.find(params[:follow_id])
    @following = current_user.unfollow(@user)
    if @following.destroy
      redirect_to @user
    else
      redirect_to @user
    end
  end
end

app/controllers/users/rooms_controller.rb
class Users::RoomsController < ApplicationController
  
  def create
    @room = Room.create
    @userRoom1 = UserRoom.create(room_id: @room.id, user_id: current_user.id)
    @userRoom2 = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    # @userRoom = UserRoom.find(params[:id])
    if UserRoom.where(user_id: current_user.id, room_id: @room.id).present?
      # ルーム内のチャットメッセージを表示させるために定義
      @chats = @room.chats
      # 新規メッセージを送信するために定義
      @chat = Chat.new
      # ルームにユーザーの名前やプロフィール画像を表示させるために定義
      @userRooms = @room.user_rooms
    else
      redirect_to user_path(current_user.id)
    end
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/posts/_post.html.erb
 <div class="post-show">

    <div class="post-detail">
      <div class="post-detail__user-name">
        <%= attachment_image_tag @post.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
        <%= link_to @post.user.name, user_path(@post.user.id) %>
      </div>

      <div class="post-detail__created_at">
        <%= @post.created_at.strftime("%Y/%m/%d %H:%M") %>
      </div>

      <div class="post-detail__post-title">
        <p>
          <%= post.title %>
        </p>
      </div>



      <div class="post-detail__post-content">

        <div class="post-detail__post-content--main">
          <p>
            <%== post.content %>
          </p>
        </div>

        <div class="post-detail__post-content--option">
          <div class="post-like">
            <% if current_user.liked_by?(post) %>
              <p>
                <%= link_to post_like_path(post.id, like.id), method: :delete, remote: true do %>
                  <i class="fas fa-heart fa-2x"></i>
                <% end %>
                <%= post.likes.count %>
                <%= link_to "いいねしたユーザーを見る", show_like_users_path(post.id) %>
              </p>
            <% else %>
              <p>
                <%= link_to post_likes_path(post.id), method: :post, remote: true do %>
                  <i class="far fa-heart fa-2x"></i>
                <% end %>
                <%= post.likes.count %>
                <%= link_to "いいねしたユーザーを見る", show_like_users_path(post.id) %>
              </p>
            <% end %>
          </div>

          <div class="post-edit-link">
            <!--他のユーザーに編集されないように条件分岐-->
            <% if post.user_id == current_user.id %>
              <%= link_to "編集する", edit_post_path(post.id), class: "btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/posts/edit.html.erb
<div class="post-edit">

  <h1>
    <i class="fas fa-edit"></i>
    投稿編集画面
  </h1>

  <div class="post-edit__edit-form">
    <%= form_with model: @post, url: post_path(@post.id), method: :patch, local: true do |f| %>
    <%= render partial: 'layouts/error_messages', locals: { model: f.object } %>
      <div class="edit-field">
        <div class="edit-field__label">
          <%= f.label :title, "タイトル" %>
        </div>
        <%= f.text_field :title %>
      </div>

      <div class="edit-field">
        <div class="edit-field__label">
          <%= f.label :content, "本文" %>
        </div>
          <%= f.text_area :content, id: 'edit_content_form' %>
      </div>
      
      
      <div class="edit-field__submit">
        <%= f.submit '変更を保存', class: "btn btn-primary btn-lg", "data-confirm" => "変更を保存します。よろしいですか？" %>
      </div>
    <% end %>
      
      <div class="post-delete">
        <%= link_to "投稿を削除する", post_path(@post.id), method: :delete, class: "btn btn-danger btn-lg", "data-confirm" => "本当に削除しますか？" %>
      </div>
  </div>
</div>



  <script>
  new FroalaEditor('#edit_content_form',{
    language: 'ja',
    imageUploadURL: '/upload_image',
    imageUploadParams: {
      id: 'my_editor'
    },
    emoticonsUseImage: false
  });
</script>

app/views/users/posts/index.html.erb
<div class="post-search">

  <%= render partial: 'users/users/user', locals: { user: @user, post: @post, isRoom: @isRoom, roomId: @roomId, room: @room, userRoom: @userRoom } %>


  <div class="post-search__result">
      <div>
        <h1>
          <i class="fas fa-search"></i>
          <%= @posts.count %>件の検索結果
        </h1>
      </div>
      <!--自分の投稿を検索するためにマイページにのみ検索バーを表示-->
      <% if @user.id == current_user.id %>
        <div class="post-search__result--search-bar">
          <%= search_form_for @q do |f| %>
            <!--タイトルと記事の内容で検索可能-->
            <%= f.search_field :title_or_content_cont, required: true, placeholder:"投稿を検索", class: "tab__post-search--form" %>
            <%= f.button :type => "submit" do %>
              <i class="tab__post-search--form fas fa-search"></i>
            <% end %>
          <% end %>
        </div>
      <% end %>

        <% if @posts.count >= 1 %>
          <div class='post-search__result--index'>
            <div class="search-result">

              <% @posts.each do |post| %>
                <article>

                  <div class="search-result__post-title">
                    <p><%= link_to post.title, post_path(post.id) %></p>
                  </div>

                  <div class="search-result__post-info">
                    <i class="fas fa-heart"></i>&nbsp;<%= post.likes.count %>
                    |
                    作成日:<%= post.created_at.strftime('%Y/%m/%d') %>
                  </div>

                </article>
              <% end %>

              <div class="search-result__paginate">
                <%= paginate @posts %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="no-result">
            <h3>キーワードに一致する記事は見つかりませんでした。</h3>
          </div>
        <% end %>
  </div>
</div>

app/views/users/posts/new.html.erb
<div class="post-new">

  <h1>
    <i class="fas fa-pencil-alt"></i>
    記事の新規投稿
  </h1>

  <div class="post-new__new-form">
  <%= form_with model: @post, url: posts_path, method: :post, local: true do |f| %>
  <%= render partial: 'layouts/error_messages', locals: { model: f.object } %>
    <div class="new-field">
      <div class="new-field__label">
        <%= f.label :title, "タイトル" %>
      </div>
      <%= f.text_field :title %>
    </div>

    <div class="new-field">
      <div class="new-field__label">
        <%= f.label :content, "本文" %>
      </div>
      <%= f.text_area :content, id: 'new_content_form' %>
    </div>

    <div class="new-field__submit">
      <%= f.submit '投稿', class: "new-post-submit btn btn-primary btn-lg", "data-confirm" => "投稿を完了します。よろしいですか?" %>
    </div>

  <% end %>
  </div>
</div>


<script>
  var editor = new FroalaEditor('#new_content_form',{
    language: 'ja',
    imageUploadURL: '/upload_image',
    imageUploadParams: {
      id: 'my_editor'
    },
    emoticonsUseImage: false
  });
</script>

app/views/users/posts/show.html.erb
<div id="post_<%= @post.id %>">
  <div class="post-show-flash">
  </div>
  <%= render partial: 'users/posts/post', locals: { post: @post, like: @like } %>
</div>

<div class="comment-heading">
  <h1>
    <i class="far fa-comment"></i>
    コメント
  </h1>
</div>

<div class="comment">
  <% if @comments.count >= 1 %>
    <% @comments.each do |comment| %>
      <div class="comment__comment-area">
        <div class="comment__comment-area--name">
          <p>
            <%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
            <%= link_to comment.user.name, user_path(comment.user.id) %>
          </p>
        </div>
        <div class="comment__comment-area--comment">
          <p>
            <%= comment.comment %>
          </p>
        </div>

        <% if comment.user.id == current_user.id %>
          <div class="comment__comment-area--delete">
            <p>
              <%= link_to "削除", post_comment_path(id: comment.id, post_id: @post.id), method: :delete, "data-confirm" => "コメントを削除しますか？" %>
            </p>
          </div>
        <% end %>
        <div class="comment__comment-area--reply">
          <%= link_to "返信する", post_new_reply_path(post_id: @post.id, id: comment.id) %>
        </div>
        <div class="comment__comment-area--created_at">
          <%= comment.created_at.strftime("%Y/%m/%d %H:%M") %>
        </div>
      </div>

        <div class="comment__reply_area">
          <% comment.replies.order(:created_at).each do |reply| %>

            <div class="comment__reply-area--to">
              <h4>
                Reply
              </h4>
            </div>
            <div class="comment__reply-area--name">
              <p>
                <%= attachment_image_tag reply.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
                <%= link_to reply.user.name, user_path(reply.user.id) %>
              </p>
            </div>
            <div class="comment__reply-area--comment">
              <p>
                <%= reply.comment %>
              </p>
            </div>

            <% if reply.user.id == current_user.id %>
              <div class="comment__reply-area--delete">
                <p>
                  <%= link_to "削除", post_comment_path(id: reply.id, post_id: @post.id), method: :delete, "data-confirm" => "返信を削除しますか？" %>
                </p>
              </div>
            <% end %>

            <div class="comment__reply-area--created_at">
              <%= reply.created_at.strftime("%Y/%m/%d %H:%M") %>
            </div>
          <% end %>
        </div>

    <% end %>
  <% else %>
    <h3>まだコメントはありません。</h3>
  <% end %>
</div>


<div class="new-comment">
  <div>
    <h3>
      <i class="far fa-comment"></i>
      コメントを投稿する
    </h3>
  </div>
  <div class="new-comment__new-field">
    <%= form_with(model: @comment, url: post_comments_path(@post.id), method: :post, local: true) do |f| %>
      <%= render partial: 'layouts/error_messages', locals: { model: f.object } %>
      <%= f.hidden_field :post_id, value: @post.id %>

      <%= f.text_area :comment, class: "comment-form" %>
    <div class="new-comment__new-field--submit">
      <%= f.submit "投稿する", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/posts/show_like_users.html.erb
<div class="post-like-users">
    
    <div class="post-like-users__heading">
      <h1>
        <%= @post.title %>にいいねしたユーザー
      </h1>
    </div>
    
    <% if @likes.count >= 1 %>
      <% @likes.each do |like| %>
        <!--退会済みユーザーを表示させないために条件分岐-->
        <% if like.user.is_deleted == false %>
          <div class="post-like-users__index">
            <div class="like-user-info">
              <div class="like-user-info__user-name">
                <p>
                  <%= attachment_image_tag like.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
                  <%= link_to like.user.name, user_path(like.user.id) %>
                </p>
              </div>
            </div>
            
            <div class="like-user-info__paginate">
              <%= paginate @likes %>
            </div>
          </div>
        <% else %>
           <div class="no-result">
              <h3>いいねしたユーザーはいません</h3>
           </div>
        <% end %>
      <% end %>
    <% else %>
    <div class="no-result">
      <h3>いいねしたユーザーはいません</h3>
    </div>
    <% end %>
    
  </div>