config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :users do
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     passwords: 'users/passwords',
     registrations: 'users/registrations'
   }
   root to: 'homes#top'
   get '/homes/about' => 'homes#about', as: 'homes_about'
   get 'users/timeline' => 'users#timeline', as: 'user_timeline'
   get 'users/:id/like_post' => 'users#like_post', as: 'user_like_post'
   get '/users/search_user_index' => 'users#search_user_index', as: 'search_user_index'
   resources :users, only: [:index, :show, :edit, :update] do
     get 'events/index' => 'events#index', as: 'events'
   end
   get '/users/:id/follow_index' => 'users#follow_index', as: 'user_follow'
   get '/users/:id/follower_index' => 'users#follower_index', as: 'user_follower'
   get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
   patch '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
   resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
     resources :likes, only: [:create, :destroy]
     resources :comments, only: [:create, :destroy]
     get '/comments/:id/new_reply' => 'comments#new_reply', as: 'new_reply'
     post '/comments/:id/reply_create' => 'comments#reply_create', as: 'reply_create'
   end
   get '/posts/:id/show_like_users' => 'posts#show_like_users', as: 'show_like_users'
   get '/posts/confirm' => 'posts#confirm', as: 'posts_confirm'
  resources :relationships, only: [:destroy, :create]
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :contacts, only: [:new, :create]
  get 'contacts/complete' => 'contacts#complete', as: 'contact_complete'
  end

  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  namespace :admins do
  get "/homes/top" => "homes#top", as: "homes"
  get '/users/search_user_index' => 'users#search_user_index', as: 'search_user_index'
  get '/users/:id/follow_index' => 'users#follow_index', as: 'user_follow'
  get '/users/:id/follower_index' => 'users#follower_index', as: 'user_follower'
  resources :users, only: [:index, :show, :update]
  get '/posts/search_post_index' => 'posts#search_post_index', as: 'search_post_index'
  resources :posts, only: [:index, :show, :destroy] do
    resources :comments, only: [:destroy]
  end
  get '/posts/:id/show_like_users' => 'posts#show_like_users', as: 'show_like_users'


  end
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  layout 'admins'
  before_action :authenticate_admin!
  before_action :set_post, only: [:show, :show_like_users, :destroy]
  def index
    @posts = Post.all.order(created_at: :desc).order(updated_at: :desc).page(params[:page]).per(10)
     # ransackの投稿内容の検索結果を表示するための変数を定義
    @q = @posts.ransack(params[:q])
    @search_posts = @q.result(distinct: true)
  end

  def search_post_index
    # ransackの投稿内容の検索結果を表示するための変数を定義
     @q = Post.ransack(params[:q])
     @posts = @q.result(distinct: true).order(created_at: :desc).order(updated_at: :desc).page(params[:page]).per(10)
  end

  def show
    # @post = Post.find(params[:id])
    @comments = @post.comments.where(parent_id: nil)
    @comment = @post.comments.new
    @comment_reply = @post.comments.new
  end

  def show_like_users
    # @post = Post.find(params[:id])
    @likes = Like.where(post_id: @post.id).order(updated_at: :desc).page(params[:page]).per(10)
  end

  def destroy
    # @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admins_posts_path
      flash[:destroy] = "投稿を削除しました。"
    else
      render :show
    end
  end
  
  
  private
  
  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :show_like_users, :edit, :update, :destroy]
  
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge({user_id: current_user.id}))
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def index
    @user = User.find(current_user.id)
    # ransackの投稿内容の検索結果を表示するための変数を定義
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).where(user_id: @user).order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    # @post = Post.find(params[:id])
    @like = @post.likes.find_by(user_id: current_user.id)
    @comments = @post.comments.where(parent_id: nil)
    @comment = @post.comments.new
    @comment_reply = @post.comments.new
    @post.comments.each do |comment|
    end

  end

  def show_like_users
    # @post = Post.find(params[:id])
    @likes = Like.where(post_id: @post.id).order(updated_at: :desc).page(params[:page]).per(10)
  end

  def edit
    # @post = Post.find(params[:id])
    # 他のユーザーがアクセスしようとしたときに遷移させないために条件分岐
    if @post.user_id != current_user.id
      if user_signed_in?
        redirect_to user_path(current_user.id)
      else
        redirect_to new_user_session_path
      end
    end
  end

  def update
    # @post = Post.find(params[:id])
    if @post.update(post_params.merge({user_id: current_user.id}))
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  private
  
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/views/admins/posts/index.html.erb
<div class="ad-post-index">

    <div class="ad-post-index__heading">
      <div class="ad-post-flash">
        <p><%= flash[:destroy] %></p>
      </div>
      <h1>
        投稿一覧
      </h1>
    </div>

    <div>
      <%= search_form_for @q, url: admins_search_post_index_path do |f| %>
        <%= f.label :title_or_content, "投稿を検索", placeholder:"タイトルと本文で検索できます。" %>
        <%= f.search_field :title_or_content_cont, required: true %>

        <%= f.button :type => "submit" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>

    <div class="ad-post-index__index">
      <div class="ad-post-info">
        <% @posts.each do |post| %>

          <div class="ad-post-info__user-name">
            <p>
              <%= attachment_image_tag post.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
              <%= link_to post.user.name,   admins_user_path(post.user.id) %>
            </p>
            <p>
              <%= link_to post.title, admins_post_path(post.id) %>
            </p>
          </div>

          <div class="ad-post-info__post-info">
            <i class="fas fa-heart"></i><%= post.likes.count %>
            |
            作成日:<%= post.created_at.strftime('%Y/%m/%d') %>
          </div>
        <% end %>
      </div>
      <div class="ad-post-info__paginate">
        <%= paginate @posts %>
      </div>
    </div>

  </div>

app/views/admins/posts/search_post_index.html.erb
<div class="ad-post-index">

    <div class="ad-post-index__heading">

      <h1>
        <%= @posts.count %>件の検索結果
      </h1>
    </div>

    <div>
    <%= search_form_for @q, url: admins_search_post_index_path do |f| %>
      <%= f.label :title_or_content, "投稿を検索", placeholder:"タイトルと本文で検索できます。" %>
      <%= f.search_field :title_or_content_cont, required: true %>

      <%= f.button :type => "submit" do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>

    <% if @posts.count >= 1 %>
    <div class="ad-post-index__index">
      <div class="ad-post-info">
        <% @posts.each do |post| %>

          <div class="ad-post-info__user-name">
            <p>
              <%= attachment_image_tag post.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
              <%= link_to post.user.name,   admins_user_path(post.user.id) %>
            </p>
            <p>
              <%= link_to post.title, admins_post_path(post.id) %>
            </p>
          </div>

          <div class="ad-post-info__post-info">
            <i class="fas fa-heart"></i><%= post.likes.count %>
            |
            作成日:<%= post.created_at.strftime('%Y/%m/%d') %>
          </div>
        <% end %>
      </div>
      <div class="ad-post-info__paginate">
        <%= paginate @posts %>
      </div>
    </div>
    <% else %>
      <div class="no-result">
        <h3>キーワードに一致する記事は見つかりませんでした。</h3>
      </div>
    <% end %>
  </div>

app/views/admins/posts/show.html.erb
<div class="ad-post-show">
  <div class="ad-post-detail">
    <div class="ad-post-detail__user-name">
      <%= attachment_image_tag @post.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
      <%= link_to @post.user.name, admins_user_path(@post.user.id) %>
    </div>

    <div class="ad-post-detail__created_at">
      <%= @post.created_at.strftime("%Y/%m/%d %H:%M") %>
    </div>

    <div class="ad-post-detail__post-title">
      <p>
        <%= @post.title %>
      </p>
    </div>



    <div class="ad-post-detail__post-content">
      <div class="ad-post-detail__post-content--main">
        <p>
          <%== @post.content %>
        </p>
      </div>

      <div class="ad-post-detail__post-content--option">
        <div class="ad-post-like">
          <p>
            <i class="fas fa-heart fa-2x"></i>
              <%= @post.likes.count %>
              <%= link_to "いいねしたユーザーを見る", admins_show_like_users_path(@post.id) %>
          </p>
        </div>

        <div class="ad-post-edit-link">
          <%= link_to "削除する", admins_post_path(@post.id), method: :delete, class: "btn btn-", "data-confirm" => "この投稿を削除します。よろしいですか？" %>
        </div>
      </div>
    </div>
  </div>
</div>
  
  
<div class="ad-comment-heading">
  <h1>
    <i class="far fa-comment"></i>
    コメント
  </h1>
</div>

<div class="ad-comment">
  <% @comments.each do |comment| %>
    <div class="ad-comment__comment-area">
      <div class="ad-comment__comment-area--name">
        <p>
          <%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
          <%= link_to comment.user.name, admins_user_path(comment.user.id) %>
        </p>
      </div>
      <div class="ad-comment__comment-area--comment">
        <p>
          <%= comment.comment %>
        </p>
      </div>
        
      <% if comment.user.id == current_user.id %>
        <div class="ad-comment__comment-area--delete">
          <p>
            <%= link_to "削除", admins_post_comment_path(id: comment.id, post_id: @post.id), method: :delete, "data-confirm" => "コメントを削除しますか？" %>
          </p>
        </div>
      <% end %>
        
      <div class="ad-comment__comment-area--created_at">
        <%= comment.created_at.strftime("%Y/%m/%d %H:%M") %>
      </div>
    </div>

  <div class="ad-comment__reply_area">
    <% comment.replies.order(:created_at).each do |reply| %>
      <div class="ad-comment__reply-area--to">
        <p>
          コメントへの返信
        </p>
      </div>
      <div class="ad-comment__reply-area--name">
        <p>
          <%= attachment_image_tag reply.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
          <%= link_to reply.user.name, admins_user_path(reply.user.id) %>
        </p>
      </div>

      <div class="ad-comment__reply-area--comment">
        <p>
          <%= reply.comment %>
        </p>
      </div>
            
      
      <div class="ad-comment__reply-area--delete">
        <p>
          <%= link_to "削除", admins_post_comment_path(id: reply.id, post_id: @post.id), method: :delete, "data-confirm" => "返信を削除しますか？" %>
        </p>
      </div>

      <div class="ad-comment__reply-area--created_at">
        <%= reply.created_at.strftime("%Y/%m/%d %H:%M") %>
      </div>
    <% end %>
  </div>
  <% end %>
  </div>

app/views/admins/posts/show_like_users.html.erb
<div class="ad-post-like-users">
    
    <div class="ad-post-like-users__heading">
      <h1>
        <%= @post.title %>にいいねしたユーザー
      </h1>
    </div>
    
    <% if @likes.count >= 1 %>
      <% @likes.each do |like| %>
        <div class="ad-post-like-users__index">
          <div class="ad-like-user-info">
            <div class="ad-like-user-info__user-name">
              <p>
                <%= attachment_image_tag like.user, :profile_image, :fill, 40, 40, format: 'jpg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "40x40" %>
                <%= link_to like.user.name, admins_user_path(like.user.id) %>
              </p>
            </div>
          </div>
          
          <div class="ad-like-user-info__paginate">
            <%= paginate @likes %>
          </div>
        </div>
      <% end %>
    <% else %>
    <div class="no-result">
      <h3>いいねしたユーザーはいません</h3>
    </div>
    <% end %>
    
  </div>