config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :users do
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     passwords: 'users/passwords',
     registrations: 'users/registrations'
   }
   root to: 'homes#top'
   get '/homes/about' => 'homes#about', as: 'homes_about'
   get 'users/timeline' => 'users#timeline', as: 'user_timeline'
   get 'users/:id/like_post' => 'users#like_post', as: 'user_like_post'
   get '/users/search_user_index' => 'users#search_user_index', as: 'search_user_index'
   resources :users, only: [:index, :show, :edit, :update] do
     get 'events/index' => 'events#index', as: 'events'
   end
   get '/users/:id/follow_index' => 'users#follow_index', as: 'user_follow'
   get '/users/:id/follower_index' => 'users#follower_index', as: 'user_follower'
   get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
   patch '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
   resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
     resources :likes, only: [:create, :destroy]
     resources :comments, only: [:create, :destroy]
     get '/comments/:id/new_reply' => 'comments#new_reply', as: 'new_reply'
     post '/comments/:id/reply_create' => 'comments#reply_create', as: 'reply_create'
   end
   get '/posts/:id/show_like_users' => 'posts#show_like_users', as: 'show_like_users'
   get '/posts/confirm' => 'posts#confirm', as: 'posts_confirm'
  resources :relationships, only: [:destroy, :create]
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :contacts, only: [:new, :create]
  get 'contacts/complete' => 'contacts#complete', as: 'contact_complete'
  end

  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  namespace :admins do
  get "/homes/top" => "homes#top", as: "homes"
  get '/users/search_user_index' => 'users#search_user_index', as: 'search_user_index'
  get '/users/:id/follow_index' => 'users#follow_index', as: 'user_follow'
  get '/users/:id/follower_index' => 'users#follower_index', as: 'user_follower'
  resources :users, only: [:index, :show, :update]
  get '/posts/search_post_index' => 'posts#search_post_index', as: 'search_post_index'
  resources :posts, only: [:index, :show, :destroy] do
    resources :comments, only: [:destroy]
  end
  get '/posts/:id/show_like_users' => 'posts#show_like_users', as: 'show_like_users'


  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
  validates :message, presence: true, length: { maximum: 1000 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
  
  validates :comment, presence: true, length: { maximum: 1000 }
  
end

app/models/contact.rb
class Contact < ApplicationRecord
  
  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true, length: { maximum: 2000 }
  
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validate :start_end_check

  def start_end_check
    # 開始時間が終了時間より前の時間を選択された場合のバリデーションエラーメッセージを追加
    if start_date > end_date
      errors.add( :end_date, "は開始時間より後の時間を入力してください。")
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
  
end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  
  # フォロー機能関連のアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  
  validates :name, presence: true
  validates :email, presence: true
  validates :introduce, length: { maximum: 500 }
  
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
     relationship = self.relationships.find_by(follow_id: other_user.id)
     if relationship
      relationship.destroy
     end
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  
  attachment :profile_image


  def liked_by?(post)
    likes.where(post_id: post.id).exists?
  end
  
  # ログイン時に退会済みユーザーを弾くためのメソッド
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/upload_controller.rb
class UploadController < ActionController::Base
  # froalaのフォームだとトークン認証に引っかかるので、認証をスキップさせる
  skip_before_action :verify_authenticity_token

  IMAGE_EXT = [".gif", ".jpeg", ".jpg", ".png", ".svg"]

  def upload_image
    if params[:file]
      FileUtils::mkdir_p(Rails.root.join("public/uploads/files"))

      ext = File.extname(params[:file].original_filename)
      ext = image_validation(ext)
      file_name = "#{SecureRandom.urlsafe_base64}#{ext}"
      path = Rails.root.join("public/uploads/files/", file_name)

      File.open(path, "wb") {|f| f.write(params[:file].read)}
      view_file = Rails.root.join("/download_file/", file_name).to_s
      render :json => {:link => view_file}.to_json

    else
      render :text => {:link => nil}.to_json
    end
  end

  def image_validation(ext)
    raise "Not allowed" unless IMAGE_EXT.include?(ext)
  end

  def access_file
    if File.exists?(Rails.root.join("public", "uploads", "files", params[:name]))
      send_data File.read(Rails.root.join("public", "uploads", "files", params[:name])), :disposition => "attachment"
    else
      render :nothing => true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/chats_helper.rb
module Users::ChatsHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/likes_helper.rb
module Users::LikesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/rooms_helper.rb
module Users::RoomsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helput</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="wrapper">
      <header>
        <div class="header-title">
          <h1>
            <%= link_to 'helput', admins_homes_path %>
          </h1>
        </div>
        <% if admin_signed_in? %>
          <nav>
            <ul class="header-list">
              <li class="header-list__header-item">
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
              </li>
              
              <li class="header-list__header-item">
                <%= link_to '投稿一覧', admins_posts_path %>
              </li>
              
              <li class="header-list__header-item">
                <%= link_to 'ユーザー一覧', admins_users_path %>
              </li>
            </ul>
          </nav>
        <% else %>
          <nav>
            <ul class="header-list">
              <li class="header-list__header-item">
                <%= link_to 'ログイン', new_admin_session_path %>
              </li>
            </ul>
          </nav>
        <% end %>
        
      </header>
      <%= yield %>
      
      <!--footerとyieldの一番下が被らないようにspacerを記述-->
      <div class="spacer">
      </div>
      <footer>
        <p class="footer-text">
          Copyright © ono ryota. All Rights Reserved.
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helput</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="wrapper">
      <header>
        <div class="header-title">
          <% if user_signed_in? %>
          <h1>
            <%= link_to 'helput', user_path(current_user.id), class: "header-title__logo" %>
          </h1>
          <% else %>
          <h1>
            <%= link_to 'helput', root_path, class: "header-title__logo" %>
          </h1>
          <% end %>
        </div>
        
        <% if user_signed_in? %>
          <!--ナビゲーションメニュー（ハンバーガーメニューを開いた時に表示される）-->
          <nav id="hamburger-nav">
            <ul>
              <li>
                <p><%= link_to 'マイページ', user_path(current_user.id) %></p>
              </li>
              <li>
                <p><%= link_to '投稿する', new_post_path %></p>
              </li>
              <li>
                <p><%= link_to 'ユーザー検索', users_path %></p>
              </li>
              <li>
                <p><%= link_to 'お問い合わせ', new_contact_path %></P>
              </li>
              <li>
                <p><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></p>
              </li>
              <li>
                <p><%= link_to '退会する', user_unsubscribe_path(current_user.id) %></p>
              </li>
            </ul>
          </nav>
          
          
          <!--ハンバーガーメニューアイコン-->
          <div id="hamburger-icon">
            <!--上の線-->
            <span></span>
            <!--真ん中の線-->
            <span></span>
            <!--下の線-->
            <span></span>
          </div>
        
        <% else %>
        <!--ログインしていない場合に表示するナビゲーションメニュー-->
          <nav>
            <ul class="header-list">
              <li class="header-list__header-item">
                <%= link_to '新規登録', new_user_registration_path %>
              </li>
              
              <li class="header-list__header-item">
                <%= link_to 'ログイン', new_user_session_path %>
              </li>
              
              <li class="header-list__header-item">
                <%= link_to 'helputについて', homes_about_path %>
              </li>
              
              <li class="header-list__header-item">
                <%= link_to 'お問い合わせ', new_contact_path %>
              </li>
            </ul>
          </nav>
        <% end %>
      </header>
      <%= yield %>
      
      <!--footerとyieldの一番下が被らないようにspacerを記述-->
      <div class="spacer">
      </div>
      <footer>
        <p class="footer-text">
          Copyright © ono ryota. All Rights Reserved.
        </p>
      </footer>
    </div>
  </body>
</html>